name: Update atom dictionary

on:
  push:
    paths:
      - "atom.py"
      - ".github/workflows/atom.yml"
  workflow_run: 
    workflows: ["Alphabeticize"]
    types:
      - completed
  

jobs:
  update-atom-dic:
    runs-on: ubuntu-latest

    name: Update Atom dictionary

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      GH_TOKEN: ${{ secrets.GIST_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Modify gist
        run: |
          wget https://gist.githubusercontent.com/ms609/b4fb9f3bf414261615dc1ba3ae76fd0a/raw/99b367ed777f494969c332396aecee1d6e5eabe0/settings.json
          python atom.py

      - name: Install gh
        run: |
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt-get update
          sudo apt-get install gh

      - name: Deploy
        run: |
          gh gist edit b4fb9f3bf414261615dc1ba3ae76fd0a -a settings.json
